### ISSUE TITLE
Breaks Google docs/sheets

### ISSUE THREAD

**Issue by tslocke** [d4rkr00t/prosemirror-dev-tools#128]
This has just started for me - I get an error as soon as I load a google sheet or a google doc. Goes away when I disable this extension.

**Comment by d4rkr00t** [comment]
Hi. This repo doesn't provide any browser extension, you are probably using a fork that does that https://github.com/TeemuKoivisto/prosemirror-dev-toolkit or this chrome extension https://chrome.google.com/webstore/detail/prosemirror-developer-too/gkgbmhfgcpfnogoeclbaiencdjkefonj
