### ISSUE TITLE
Dev Tools no longer work in ProseMirror v0.23+

### ISSUE THREAD

**Issue by 5id** [d4rkr00t/prosemirror-dev-tools#77]
After bumping my PM version to 0.23 I get the follow error:
```
ERROR in /~/prosemirror-dev-tools/dist/cjs/state/modules/editor/index.js
Module not found: Error: Cannot resolve module 'prosemirror-model/dist/to_dom' in /node_modules/prosemirror-dev-tools/dist/cjs/state/modules/editor
 @ /~/prosemirror-dev-tools/dist/cjs/state/modules/editor/index.js 24:14-54
```

It appears to be as a result of:
```
import { DOMSerializer } from "prosemirror-model/dist/to_dom";
```

In PM v0.23, you should be able to import DOMSerializer directly via 'prosemirror-model'. I'm not sure if that will be backwards compatible with previous PM versions? Was there a reason for importing directly from to_dom in the first place?

**Comment by d4rkr00t** [comment]
Wow, thanks, I'll fix that :)
