### ISSUE TITLE
Cannot install v2.0.0

### ISSUE THREAD

**Issue by marcelkorpel** [d4rkr00t/prosemirror-dev-tools#84]
When I try to install this package 'the npm way' I am not able to install v2.0.0. I already tried removing `~/.npm` and local `node_modules`, but it always errors with

    14 http fetch GET 200 https://registry.npmjs.org/prosemirror-dev-tools 141ms
    15 silly registry:manifest no matching version for prosemirror-dev-tools@^2.0.0 in the cache. Forcing revalidation
    16 http fetch GET 304 https://registry.npmjs.org/prosemirror-dev-tools 27ms (from cache)
    17 silly fetchPackageMetaData error for prosemirror-dev-tools@^2.0.0 No matching version found for prosemirror-dev-tools@^2.0.0
    18 silly registry:manifest no matching version for prosemirror-dev-tools@^2.0.0 in the cache. Forcing revalidation
    19 http fetch GET 304 https://registry.npmjs.org/prosemirror-dev-tools 20ms (from cache)
    20 silly fetchPackageMetaData error for prosemirror-dev-tools@^2.0.0 No matching version found for prosemirror-dev-tools@^2.0.0

in the log. When I run

    $ npm install --save-dev prosemirror-dev-tools

npm installs v1.4.0. However, when navigating to the registry page, I get a JSON string back, which clearly states that the latest version is 2.0.0.

**Comment by d4rkr00t** [comment]
Hey, thanks for the report. I don't know what went wrong with that release, but i just published 2.0.1 and it seems like working properly :)
