### ISSUE TITLE
codepen example is broken becasue pkgzip is deprecated

### ISSUE THREAD

**Issue by beckiechoi** [d4rkr00t/prosemirror-dev-tools#85]
The [codepen example](https://codepen.io/iamsysoev/pen/QvpELv) is broken currently.
[pkgzip.com](https://pkgzip.com) is no longer in service, and their [bitbucket page](https://bitbucket.org/atlassian/pkgzip) says it's deprecated.

**Comment by d4rkr00t** [comment]
Unfortunately there is not much i can do about that :( 

I'd updated codesandbox example so it's working and I removed a link to a codepen since it's broken anyway...
