### ISSUE TITLE
Add support for Block marks

### ISSUE THREAD

**Issue by nathf** [d4rkr00t/prosemirror-dev-tools#95]
There's support for Inline Node marks here:
https://github.com/d4rkr00t/prosemirror-dev-tools/blob/52ca4cb5b85a5ce377743859e15d858f74b93c16/src/tabs/structure.js#L159-L162

But you can also apply them to block nodes. I'll try raise a PR later for this.

**Comment by torifat** [comment]
@nathf mate, where's the PR?
